'use strict';
const $=id=>document.getElementById(id),s={root:null,editor:null,files:new Map(),active:null,token:null,backend:null,socket:null,conversation:null,turn:null,blocked:new Set(),stream:null,process:null,prefs:{},recording:null,audio:null,queue:[]};
const languages={py:'python',js:'javascript',ts:'typescript',tsx:'typescript',jsx:'javascript',json:'json',html:'html',css:'css',md:'markdown',cs:'csharp',dart:'dart',rs:'rust',go:'go',sh:'shell'};
let toastTimer,diagnosticTimer,lastProgress=0;
const motion=window.WednesdayMotion;
function activity(text,phase="idle"){document.body.dataset.state=phase;$("assistant-status").textContent=text;$("assistant-form").setAttribute("aria-busy",String(phase==="thinking"));$("voice").setAttribute("aria-pressed",String(phase==="listening"));motion.pulse(document.querySelector(".small-orb"));}
function toast(text){$('toast').textContent=text;$('toast').hidden=false;motion.enter($('toast'));clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,6000);}
function node(tag,text,className){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(className)e.className=className;return e;}
function action(label,fn){const b=node('button',label);b.type='button';b.onclick=()=>Promise.resolve(fn()).catch(e=>toast(e.message));return b;}
const api=(route,method='GET',body)=>window.aura.api(route,method,body);
function terminal(text){$('terminal-output').textContent+=text;$('terminal-output').scrollTop=$('terminal-output').scrollHeight;}
function field(label,name,value='',type='text',choices){const line=node('label',label,'field');const input=node(choices?'select':type==='textarea'?'textarea':'input');input.name=name;if(!choices&&type!=='textarea')input.type=type;if(choices)choices.forEach(choice=>{const option=node('option',choice);option.value=choice;input.append(option);});input.value=value;line.append(input);return line;}
function dialog(title,content,submit,buttonLabel='Save'){
  $('dialog-heading').textContent=title;$('dialog-content').replaceChildren(...content);$('dialog-actions').hidden=!submit;$('dialog-submit').textContent=buttonLabel;$('dialog-form').onsubmit=async event=>{event.preventDefault();const b=event.submitter;b.disabled=true;try{await submit(Object.fromEntries(new FormData(event.currentTarget)));await motion.close($('dialog'));}catch(error){toast(error.message);}finally{b.disabled=false;}};$('dialog').showModal();motion.enter($('dialog'));
}
function theme(){document.documentElement.dataset.palette=s.prefs.palette||"amethyst";const appearance=s.prefs.theme==='system'?(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'):s.prefs.theme||'dark';document.documentElement.dataset.theme=appearance;document.documentElement.dataset.reduceMotion=String(!!s.prefs.reduce_motion);document.documentElement.dataset.reduceTransparency=String(!!s.prefs.reduce_transparency);document.documentElement.dataset.highContrast=String(!!s.prefs.high_contrast);if(s.editor){monaco.editor.setTheme(s.prefs.high_contrast?(appearance==='light'?'hc-light':'hc-black'):(appearance==='light'?'aura-pearl':'aura-graphite'));s.editor.updateOptions({smoothScrolling:!(s.prefs.reduce_motion||matchMedia('(prefers-reduced-motion:reduce)').matches)});}}
async function openFolder(){if([...s.files.values()].some(file=>file.dirty)&&!confirm('Open another workspace and discard unsaved edits?'))return;const root=await window.aura.openFolder();if(!root)return;for(const file of s.files.values())file.model.dispose();s.files.clear();s.active=null;send({type:'code_context',file:'',content:''});$('context-note').textContent='No file selected · context is explicit';s.root=root;$('project-name').textContent=root.split(/[\\/]/).pop();$('file-tree').replaceChildren();await tree(root,$('file-tree'),0);tabs();$('editor-welcome').hidden=false;}
async function tree(path,container,depth){const entries=await window.aura.listDir(path);for(const entry of entries){const row=action((entry.isDir?'▸ ':'· ')+entry.name,async()=>{if(entry.isDir){if(row.nextSibling?.dataset?.folder===entry.path){row.nextSibling.remove();return;}const nested=node('div');nested.dataset.folder=entry.path;row.after(nested);motion.enter(nested);await tree(entry.path,nested,depth+1);}else await openFile(entry.path,entry.name);});row.className='tree-file'+(entry.isDir?' tree-folder':'');row.style.paddingLeft=8+depth*12+'px';container.append(row);}}
function language(path){return languages[path.split('.').pop().toLowerCase()]||'plaintext';}
async function openFile(path,name){if(!s.editor)throw new Error('Editor is still loading.');if(!s.files.has(path)){const content=await window.aura.readFile(path);const model=monaco.editor.createModel(content,language(path),monaco.Uri.file(path));s.files.set(path,{name:name||path.split(/[\\/]/).pop(),model,dirty:false});model.onDidChangeContent(()=>{s.files.get(path).dirty=true;tabs();scheduleDiagnostics();});}s.active=path;s.editor.setModel(s.files.get(path).model);$('editor-welcome').hidden=true;motion.enter(document.querySelector('.editor-body'));$('file-status').textContent=path;$('language-status').textContent=language(path);$('context-note').textContent=s.files.get(path).name+' · selected file context';tabs();scheduleDiagnostics();}
function tabs(){$('tabs').replaceChildren();s.files.forEach((file,path)=>{const tab=node('div',undefined,'tab'+(path===s.active?' selected':''));const title=action(file.name+(file.dirty?' •':''),()=>openFile(path,file.name));const close=action('×',()=>{if(file.dirty&&!confirm('Discard unsaved edits in '+file.name+'?'))return;file.model.dispose();s.files.delete(path);if(s.active===path){s.active=null;const next=s.files.keys().next().value;if(next)openFile(next);else{$('editor-welcome').hidden=false;s.editor.setModel(null);send({type:'code_context',file:'',content:''});$('context-note').textContent='No file selected · context is explicit';}}tabs();});close.setAttribute('aria-label','Close '+file.name);tab.append(title,close);$('tabs').append(tab);});}
async function save(){if(!s.active)throw new Error('Select a file first.');const file=s.files.get(s.active);await window.aura.writeFile(s.active,file.model.getValue());file.dirty=false;tabs();$('file-status').textContent='Saved · '+file.name;motion.enter($('file-status'));}
function newFile(){if(!s.root)throw new Error('Select a workspace first.');dialog('Create a file',[field('Relative filename · parent folder must exist','name')],async data=>{if(!data.name.trim())throw new Error('Enter a filename.');const target=s.root+'/'+data.name;await window.aura.createFile(target);await openFile(target,data.name.split(/[\\/]/).pop());await refresh();},'Create');}
async function refresh(){if(!s.root)return;$('file-tree').replaceChildren();await tree(s.root,$('file-tree'),0);}
function scheduleDiagnostics(){clearTimeout(diagnosticTimer);diagnosticTimer=setTimeout(async()=>{if(!s.active)return;const file=s.files.get(s.active),model=file.model;const current=s.active;try{const result=await api('code/diagnostics','POST',{code:model.getValue()||' ',language:language(current)});if(current!==s.active||model.isDisposed())return;if(result.supported)monaco.editor.setModelMarkers(model,'Wednesday',(result.diagnostics||[]).map(d=>({severity:monaco.MarkerSeverity.Error,message:d.message,startLineNumber:d.line||1,endLineNumber:d.line||1,startColumn:d.column||1,endColumn:(d.column||1)+1})));const markers=monaco.editor.getModelMarkers({resource:model.uri});$('diagnostic-status').textContent=markers.length?markers.length+' diagnostic'+(markers.length===1?'':'s'):'No diagnostics';}catch{$('diagnostic-status').textContent='Local editor diagnostics';}},450);}
async function checkpoint(){if(!s.root)throw new Error('Select a workspace first.');if([...s.files.values()].some(f=>f.dirty))throw new Error('Save unsaved files before creating a Git checkpoint.');dialog('Save a Git checkpoint',[field('Commit message','message')],async data=>{const result=await window.aura.checkpoint(data.message);terminal(result.out+'\n');if(!result.ok)throw new Error(result.error||result.out||'Git checkpoint failed.');toast('Checkpoint saved.');});}
async function gitHistory(){const result=await window.aura.gitLog();if(!result.ok)throw new Error(result.out||'No Git history found.');const list=node('div',undefined,'dialog-list');result.out.trim().split('\n').filter(Boolean).forEach(line=>{const [hash,title,date]=line.split('\t');list.append(action(title+' · '+date,async()=>{const diff=await window.aura.gitDiff(hash);dialog('Checkpoint changes',[node('pre',diff.out,'dialog-list')]);}));});dialog('Git history',[list]);}
function addMessage(role,text){const row=node('article',undefined,'message');row.append(node('small',role==='user'?'You':'Wednesday'));const body=node('p',text);row.append(body);$('assistant-messages').append(row);motion.enter(row);$('assistant-messages').scrollTop=$('assistant-messages').scrollHeight;return body;}
function stopAudio(){s.queue=[];if(s.audio){s.audio.pause();URL.revokeObjectURL(s.audio.src);s.audio=null;}}
function playAudio(){if(s.audio||!s.queue.length)return;const data=s.queue.shift();if(s.blocked.has(data.turn_id)){playAudio();return;}const bytes=Uint8Array.from(atob(data.audio_b64),c=>c.charCodeAt(0));const url=URL.createObjectURL(new Blob([bytes],{type:data.audio_format==='wav'?'audio/wav':'audio/mpeg'}));const audio=new Audio(url);s.audio=audio;audio.onended=()=>{URL.revokeObjectURL(url);if(s.audio===audio){s.audio=null;playAudio();}};audio.play().catch(error=>{toast(error.message);URL.revokeObjectURL(url);s.audio=null;});}
function send(data){if(s.socket?.readyState!==WebSocket.OPEN)throw new Error('Wait for the Wednesday workspace to connect.');s.socket.send(JSON.stringify(data));}
function connect(){if(s.socket){s.socket.onclose=null;s.socket.close();}const url=new URL('/ws',s.backend);url.protocol=url.protocol==='https:'?'wss:':'ws:';if(s.conversation)url.searchParams.set('conversation_id',s.conversation);const socket=new WebSocket(url,['wednesday.v1','token.'+s.token]);s.socket=socket;
  socket.onopen=()=>{activity('Workspace connected');};socket.onclose=()=>{activity('Disconnected · reopen history to reconnect');stopAudio();};
  socket.onmessage=event=>{const data=JSON.parse(event.data);if(data.type==='session'){s.conversation=data.conversation_id;$('assistant-messages').replaceChildren();(data.history||[]).forEach(m=>addMessage(m.role,m.content));return;}
    if(data.type==='stream_start'){s.turn=data.turn_id;s.stream=addMessage('assistant','');activity('Thinking through your request…','thinking');}
    if(s.blocked.has(data.turn_id)&&data.type!=='interrupted')return;
    if(data.type==='stream_chunk'&&s.stream){s.stream.textContent+=data.content;if(performance.now()-lastProgress>350){lastProgress=performance.now();motion.pulse(document.querySelector('.small-orb'));}$('assistant-messages').scrollTop=$('assistant-messages').scrollHeight;}
    else if(data.type==='stream_end'){s.stream=null;activity('Ready when you are');}
    else if(data.type==='response'||data.type==='transcript')addMessage(data.type==='transcript'?'user':'assistant',data.content);
    else if(data.type==='audio_chunk'){s.queue.push(data);playAudio();}
    else if(data.type==='interrupted'){stopAudio();s.stream=null;activity('Interrupted');}
    else if(['error','stt_error','speech_unavailable'].includes(data.type)){toast(data.content);activity('Engine unavailable');}
    else if(data.type==='reminder'){toast(data.content);send({type:'reminder_ack',reminder_id:data.reminder_id});}
  };
}
async function ask(prompt){if(!prompt.trim())return;stopAudio();if(s.active){const file=s.files.get(s.active);send({type:'code_context',file:file.name,content:file.model.getValue().slice(0,12000),language:language(s.active)});}else send({type:'code_context',file:'',content:''});send({type:'text',content:prompt,tts:!!s.prefs.tts});addMessage('user',prompt);$('assistant-input').value='';activity('Starting your turn…','thinking');}
function interrupt(){if(s.turn)s.blocked.add(s.turn);stopAudio();send({type:'interrupt'});}
async function voice(){if(s.recording){s.recording.stop();return;}if(!navigator.mediaDevices?.getUserMedia)throw new Error('Microphone recording is unavailable.');const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true}});const recorder=new MediaRecorder(stream),chunks=[];s.recording=recorder;$('voice').textContent='Send voice';activity('Listening · press Send voice to finish','listening');recorder.ondataavailable=e=>chunks.push(e.data);recorder.onstop=()=>{stream.getTracks().forEach(t=>t.stop());s.recording=null;$('voice').textContent='Voice';activity('Processing your voice…','thinking');const reader=new FileReader();reader.onload=()=>send({type:'audio',audio_b64:reader.result.split(',')[1],language:s.prefs.language||'en',tts:!!s.prefs.tts});reader.readAsDataURL(new Blob(chunks,{type:recorder.mimeType}));};recorder.start();setTimeout(()=>{if(recorder.state==='recording')recorder.stop();},45000);}
async function preferences(){dialog('Your coding environment',[field('Appearance','theme',s.prefs.theme||'system','text',['system','light','dark']),field('Signature palette','palette',s.prefs.palette||'amethyst','text',['amethyst','lagoon','ember']),field('Provider','llm_provider',s.prefs.llm_provider||'ollama','text',['ollama','groq','openai','gemini']),field('Local model','ollama_model',s.prefs.ollama_model||'llama3.1:8b'),field('Cloud model','llm_model',s.prefs.llm_model||'llama-3.1-8b-instant'),field('Response style · optional','persona',s.prefs.persona||'','textarea'),field('Reduce motion','reduce_motion',String(!!s.prefs.reduce_motion),'text',['false','true']),field('Reduce transparency','reduce_transparency',String(!!s.prefs.reduce_transparency),'text',['false','true']),field('High contrast','high_contrast',String(!!s.prefs.high_contrast),'text',['false','true']),field('Speak responses','tts',String(!!s.prefs.tts),'text',['false','true'])],async data=>{['reduce_motion','reduce_transparency','high_contrast','tts'].forEach(k=>data[k]=data[k]==='true');s.prefs=await api('preferences','PATCH',data);theme();});}
async function memories(){const data=await api('memories');const list=node('div',undefined,'dialog-list');list.append(action('＋ Save a new memory',()=>dialog('New memory',[field('Title','title'),field('Remember this','content','','textarea')],data=>api('memories','POST',data))));data.memories.forEach(memory=>{const row=node('article');row.append(node('h3',memory.title),node('p',memory.content),action('Edit',()=>dialog('Edit memory',[field('Title','title',memory.title),field('Content','content',memory.content,'textarea')],data=>api('memories/'+memory.id,'PATCH',data))),action('Remove',async()=>{await api('records/'+memory.id,'DELETE');row.remove();}));list.append(row);});dialog('Wednesday memory',[list]);}
async function sessions(){const data=await api('conversations');const list=node('div',undefined,'dialog-list');list.append(action('＋ New conversation',async()=>{const result=await api('conversations','POST',{});s.conversation=result.id;connect();$('dialog').close();}));data.conversations.forEach(c=>list.append(action(c.title,()=>{s.conversation=c.id;connect();$('dialog').close();})));dialog('Your conversations',[list]);}
const commands=[['Open workspace',openFolder],['New file',newFile],['Save current file',save],['Refresh explorer',refresh],['Review selected code',()=>ask('Review the selected code. Explain concrete improvements.')],['Explain selected code',()=>ask('Explain what the selected code does.')],['Save Git checkpoint',checkpoint],['Git history',gitHistory],['Preferences',preferences],['Search conversations',sessions],['Memory',memories],['Export workspace',()=>window.aura.export()]];
function palette(){const search=field('Find a command','search');const list=node('div',undefined,'dialog-list');function render(query=''){list.replaceChildren();commands.filter(([name])=>name.toLowerCase().includes(query.toLowerCase())).forEach(([name,fn])=>list.append(action(name,async()=>{$('dialog').close();await fn();})));}search.querySelector('input').oninput=e=>render(e.target.value);render();dialog('Commands',[search,list]);search.querySelector('input').focus();}
function on(id,fn){$(id).onclick=()=>Promise.resolve().then(fn).catch(error=>toast(error.message));}
on('open-folder',openFolder);on('welcome-open',openFolder);on('new-file',newFile);on('refresh',refresh);on('checkpoint',checkpoint);on('git-history',gitHistory);on('export',()=>window.aura.export());on('preferences',preferences);on('palette-open',palette);on('review',()=>{if(!s.active)throw new Error('Select a file to review.');return ask('Review this selected file and explain actionable improvements.');});on('memories',memories);on('sessions',sessions);on('new-chat',async()=>{const c=await api('conversations','POST',{});s.conversation=c.id;connect();});on('interrupt',interrupt);on('voice',voice);on('selected-image',async()=>{const image=await window.aura.selectImage();if(image){send({type:'screen',image_b64:image.base64,prompt:'Help me understand this selected image.'});addMessage('user','Selected image: '+image.name);}});
$('dialog-close').onclick=$('dialog-cancel').onclick=()=>motion.close($('dialog'));$('dialog').addEventListener('cancel',event=>{event.preventDefault();motion.close($('dialog'));});$('terminal-clear').onclick=()=>$('terminal-output').textContent='';on('terminal-stop',()=>s.process?window.aura.cancelProcess(s.process):false);
$('terminal-form').onsubmit=async e=>{e.preventDefault();const command=$('terminal-input').value.trim();if(!command)return;try{terminal('› '+command+'\n');const result=await window.aura.terminal(command);s.process=result.id;document.querySelector('.terminal').setAttribute('aria-busy','true');motion.enter(document.querySelector('.terminal'));$('terminal-input').value='';}catch(error){terminal(error.message+'\n');}};
window.aura.onTerminalData(data=>terminal(data.text));window.aura.onTerminalExit(result=>{terminal('\nProcess exited · '+(result.code??result.error)+'\n');if(s.process===result.id){s.process=null;document.querySelector('.terminal').setAttribute('aria-busy','false');motion.enter($('diagnostic-status'));}});
$('assistant-form').onsubmit=e=>{e.preventDefault();ask($('assistant-input').value).catch(error=>toast(error.message));};$('assistant-input').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('assistant-form').requestSubmit();}};
document.addEventListener('keydown',e=>{if(!(e.ctrlKey||e.metaKey))return;const fn=({s:save,o:openFolder,k:palette})[e.key.toLowerCase()];if(fn){e.preventDefault();Promise.resolve().then(fn).catch(error=>toast(error.message));}});
window.addEventListener('beforeunload',e=>{if([...s.files.values()].some(f=>f.dirty)){e.preventDefault();e.returnValue='Unsaved edits';}});
(()=>{
  monaco.editor.defineTheme('aura-graphite',{base:'vs-dark',inherit:true,rules:[{token:'comment',foreground:'95A0BA'},{token:'keyword',foreground:'C5B8FA'},{token:'string',foreground:'A1D9C3'},{token:'number',foreground:'BED0E2'}],colors:{'editor.background':'#191E2B','editor.foreground':'#F2F0EB','editorLineNumber.foreground':'#8993AC','editorLineNumber.activeForeground':'#C5B8FA','editor.lineHighlightBackground':'#252B3C','editor.selectionBackground':'#A18BCF42','editorCursor.foreground':'#D6CCFB','editorIndentGuide.background1':'#BCC5DF22'}});
  monaco.editor.defineTheme('aura-pearl',{base:'vs',inherit:true,rules:[{token:'comment',foreground:'626C80'},{token:'keyword',foreground:'6B54AA'},{token:'string',foreground:'2E765F'},{token:'number',foreground:'526C84'}],colors:{'editor.background':'#FFFEFA','editor.foreground':'#242B3D','editorLineNumber.foreground':'#626C80','editorLineNumber.activeForeground':'#6B54AA','editor.lineHighlightBackground':'#F0EDF4','editor.selectionBackground':'#9A86C533','editorCursor.foreground':'#6B54AA','editorIndentGuide.background1':'#4F597822'}});
  s.editor=monaco.editor.create($('editor'),{theme:'aura-graphite',model:null,fontFamily:'Cascadia Code, Consolas, monospace',fontSize:13,lineHeight:23,minimap:{enabled:false},padding:{top:20,bottom:20},automaticLayout:true,scrollBeyondLastLine:false,smoothScrolling:true});theme();
})();
window.aura.bootstrap().then(session=>{s.token=session.token;s.backend=session.backend;s.prefs=session.preferences;theme();connect();}).catch(error=>{activity('Start the Wednesday backend');toast(error.message);});

// Pointer highlights update only the floating interaction material, at most once per frame.
(() => {
  let frame=0, point;
  const enabled=()=>!matchMedia('(prefers-reduced-motion: reduce)').matches && document.documentElement.dataset.reduceMotion!=='true';
  document.addEventListener('pointermove',event=>{
    if(!enabled())return;
    const surface=event.target.closest('.glass,.topbar,.rail,.chat-composer,dialog,.header-actions');
    if(!surface)return;
    point={surface,x:event.clientX,y:event.clientY};
    if(frame)return;
    frame=requestAnimationFrame(()=>{frame=0;const {surface,x,y}=point;const rect=surface.getBoundingClientRect();if(!rect.width||!rect.height)return;surface.style.setProperty('--glass-x',`${Math.round((x-rect.left)/rect.width*100)}%`);surface.style.setProperty('--glass-y',`${Math.round((y-rect.top)/rect.height*100)}%`);});
  },{passive:true});
})();

matchMedia('(prefers-color-scheme:dark)').addEventListener('change',()=>{if(s.prefs.theme==='system')theme();});
matchMedia('(prefers-reduced-motion:reduce)').addEventListener('change',theme);
