'use strict';
// Run against an isolated Wednesday service. Uses a fresh browser owner.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path');
const base=process.env.WEDNESDAY_URL||'http://127.0.0.1:8006';
const output=path.resolve(__dirname,'../../test-results/browser');
let runningBrowser;
(async()=>{
  await fs.mkdir(output,{recursive:true});
  const browser=await chromium.launch({channel:process.env.PLAYWRIGHT_CHANNEL||'chrome',headless:true,slowMo:process.env.RECORD_DEMO?180:0});
  runningBrowser=browser;
  const context=await browser.newContext({viewport:{width:1440,height:1000},colorScheme:'dark',...(process.env.RECORD_DEMO?{recordVideo:{dir:path.resolve(__dirname,'../../docs/demo'),size:{width:1440,height:1000}}}:{})});
  const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
  const beat=()=>process.env.RECORD_DEMO?new Promise(resolve=>setTimeout(resolve,1500)):Promise.resolve();
  await page.goto(base+'/ui/');await page.getByText('Workspace connected',{exact:true}).waitFor();
  await page.screenshot({path:path.join(output,'wednesday-desktop-dark.png'),fullPage:true});
  await beat();
  await page.locator('#navigation [data-view="memory"]').click();
  await page.getByRole('button',{name:'＋ Add memory',exact:true}).click();
  await page.locator('[name=title]').fill('Portfolio acceptance memory');
  await page.locator('[name=content]').fill('The launch target is December.');
  await page.locator('#editor-form button[type=submit]').click();
  await page.getByRole('heading',{name:'Portfolio acceptance memory',exact:true}).waitFor();
  await beat();
  await page.reload();await page.getByText('Workspace connected',{exact:true}).waitFor();
  await page.locator('#navigation [data-view="memory"]').click();
  await page.getByRole('heading',{name:'Portfolio acceptance memory',exact:true}).waitFor();
  await page.locator('#navigation [data-view="knowledge"]').click();
  await page.locator('#document-input').setInputFiles({name:'acceptance.md',mimeType:'text/markdown',buffer:Buffer.from('The launch target is December and the release is local first.')});
  await page.getByRole('heading',{name:'acceptance.md',exact:true}).waitFor();
  await beat();
  await page.locator('#navigation [data-view="reminders"]').click();
  await page.getByRole('button',{name:'＋ Schedule reminder',exact:true}).click();
  await page.locator('[name=text]').fill('Review portfolio launch');
  await page.locator('[name=local_time]').fill('2027-12-01T09:00');
  await page.locator('#editor-form button[type=submit]').click();
  await page.getByRole('heading',{name:'Review portfolio launch',exact:true}).waitFor();
  await beat();
  await page.getByRole('button',{name:'Cancel',exact:true}).click();
  await page.getByText(/cancelled ·/).waitFor();
  await beat();
  await page.locator('#navigation [data-view="tools"]').click();
  await page.getByRole('button',{name:'Run a tool',exact:true}).click();
  await page.locator('#editor-form button[type=submit]').click();
  await page.locator('#navigation [data-view="tools"]').click();
  await page.getByRole('heading',{name:'time',exact:true}).waitFor();
  await beat();
  await page.getByRole('button',{name:'＋ Save workflow',exact:true}).click();
  await page.locator('[name=title]').fill('Morning check');
  await page.locator('[name=steps]').fill('time');
  await page.locator('#editor-form button[type=submit]').click();
  await page.getByRole('button',{name:'Run workflow',exact:true}).click();
  await beat();
  await page.locator('[data-view=settings]').first().click();
  await page.locator('[name=theme]').selectOption('light');
  await page.locator('[name=reduce_motion]').check();
  await page.locator('[name=reduce_transparency]').check();
  await page.getByRole('button',{name:'Save preferences',exact:true}).click();
  await page.waitForFunction(()=>document.documentElement.dataset.theme==='light');
  assert.equal(await page.locator('html').getAttribute('data-reduce-motion'),'true');
  await page.locator('#navigation [data-view="chat"]').click();
  await page.screenshot({path:path.join(output,'wednesday-desktop-light.png'),fullPage:true});
  await page.locator('#prompt').fill('Which month is the launch target?');
  await page.getByRole('button',{name:'Send message',exact:true}).click();
  // This fixture intentionally has no model installed. A failed engine must
  // display a failure, never a fabricated assistant completion.
  await page.locator('#messages').getByText('The requested engine could not complete this turn.',{exact:false}).waitFor();
  const download=page.waitForEvent('download');await page.locator('#export').click();
  const exported=await download;await exported.saveAs(path.join(output,'workspace-export.json'));
  const data=JSON.parse(await fs.readFile(path.join(output,'workspace-export.json'),'utf8'));
  assert(data.records.some(r=>r.title==='Portfolio acceptance memory'));
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:path.join(output,'wednesday-mobile-light.png'),fullPage:true});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Mobile has horizontal overflow');
  await page.getByRole('button',{name:'Preferences',exact:true}).first().click();
  await page.getByRole('button',{name:'Save preferences',exact:true}).waitFor();
  await page.screenshot({path:path.join(output,'wednesday-mobile-settings.png'),fullPage:true});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Mobile settings overflow');
  const other=await browser.newContext();const privatePage=await other.newPage();await privatePage.goto(base+'/ui/');await privatePage.getByText('Workspace connected',{exact:true}).waitFor();
  await privatePage.locator('#navigation [data-view="memory"]').click();
  assert.equal(await privatePage.getByRole('heading',{name:'Portfolio acceptance memory',exact:true}).count(),0);
  assert.deepEqual(errors,[]);
  await fs.writeFile(path.join(output,'acceptance.json'),JSON.stringify({passed:true,checks:['owned memory CRUD and reload','document upload','reminder schedule/cancel','tool receipts','workflow execution','persistent preferences','provider failure displayed','JSON export','390px layout','private owner isolation'],pageErrors:errors},null,2));
  const video=page.video();await context.close();if(video)await video.saveAs(path.resolve(__dirname,'../../docs/demo/wednesday-acceptance.webm'));await browser.close();console.log('Wednesday browser acceptance passed.');
})().catch(async error=>{console.error(error);if(runningBrowser)await runningBrowser.close();process.exit(1);});
