'use strict';
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path');
const base=process.env.WEDNESDAY_URL||'http://127.0.0.1:8021';
const output=path.resolve(__dirname,'../../test-results/premium-motion/browser');
let browser;
(async()=>{
  await fs.mkdir(output,{recursive:true});
  browser=await chromium.launch({channel:'chrome',headless:true,args:['--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream']});
  const context=await browser.newContext({viewport:{width:1440,height:1000},colorScheme:'dark',permissions:['microphone']}),page=await context.newPage(),errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  await page.goto(base+'/ui/');await page.getByText('Workspace connected',{exact:true}).waitFor();
  await page.evaluate(()=>showView('memory'));
  assert(await page.locator('#panel-view').evaluate(node=>node.getAnimations().some(a=>a.playState==='running')),'Panel entry did not animate');
  await page.evaluate(()=>document.querySelector('#panel-view .primary').click());
  assert(await page.locator('#editor-dialog').evaluate(node=>node.getAnimations().some(a=>a.playState==='running')),'Dialog entry did not animate');
  await page.screenshot({path:path.join(output,'wednesday-motion-dialog.png'),animations:'allow'});
  await page.evaluate(()=>document.querySelector('#dialog-cancel').click());
  assert(await page.locator('#editor-dialog').evaluate(node=>node.open),'Exit removed modal before its transition');
  await page.waitForFunction(()=>!document.querySelector('#editor-dialog').open);
  // A slow old panel response cannot overwrite the selected route.
  await page.route('**/api/memories',async route=>{await new Promise(resolve=>setTimeout(resolve,350));await route.continue();});
  await page.evaluate(()=>{showView('memory');showView('knowledge');});
  await page.getByRole('heading',{name:'Keep your context close.'}).waitFor();await page.waitForTimeout(450);
  assert.equal(await page.locator('#view-title').textContent(),'Knowledge');assert.equal(await page.getByRole('heading',{name:'Remember what matters.'}).count(),0);await page.unroute('**/api/memories');
  for(const palette of ['amethyst','lagoon','ember']){await page.evaluate(palette=>savePreferences({palette}),palette);await page.reload();await page.getByText('Workspace connected',{exact:true}).waitFor();assert.equal(await page.locator('html').getAttribute('data-palette'),palette);}
  await page.screenshot({path:path.join(output,'wednesday-ember-dark.png'),animations:'allow'});
  await page.evaluate(()=>showView('chat'));await page.locator('#prompt').fill('Motion acceptance request');
  await page.evaluate(()=>document.querySelector('#composer').requestSubmit());
  assert.equal(await page.locator('body').getAttribute('data-state'),'thinking');assert.equal(await page.locator('#composer').getAttribute('aria-busy'),'true');
  assert(await page.locator('.activity-orb').evaluate(node=>node.getAnimations().some(a=>a.playState==='running')),'Live turn did not pulse');
  await page.locator('#messages').getByText('The requested engine could not complete this turn.',{exact:false}).waitFor();
  assert.equal(await page.locator('#composer').getAttribute('aria-busy'),'false');
  await page.evaluate(()=>savePreferences({reduce_motion:false}));
  await page.evaluate(()=>showView('memory'));
  await page.evaluate(()=>savePreferences({reduce_motion:true}));
  assert.equal(await page.evaluate(()=>document.getAnimations().filter(a=>a.playState==='running').length),0,'Reduced motion did not cancel current animation');
  await page.evaluate(()=>showView('chat'));assert.equal(await page.locator('#chat-view').evaluate(n=>n.getAnimations().length),0);
  await page.evaluate(()=>toggleRecording());await page.waitForFunction(()=>!!state.recording);
  assert.equal(await page.locator('#mic').getAttribute('aria-pressed'),'true');await page.waitForTimeout(600);
  assert.equal(await page.locator('.orb').evaluate(n=>n.style.transform),'','Reduced recording still moved orb');
  await page.evaluate(()=>toggleRecording());await page.waitForFunction(()=>!state.recording);await page.waitForTimeout(350);
  await page.evaluate(()=>savePreferences({reduce_motion:false,palette:'lagoon',theme:'light'}));
  await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>showView('settings'));
  assert.equal(await page.evaluate(()=>document.getAnimations().filter(a=>a.playState==='running').length),0,'OS preference did not suppress animation');
  await page.emulateMedia({reducedMotion:'no-preference'});await page.evaluate(()=>showView('chat'));
  await page.waitForTimeout(700);
  assert.equal(await page.evaluate(()=>document.getAnimations().filter(a=>a.effect.getTiming().iterations===Infinity).length),0,'Continuous busy or idle animation exists');
  await page.screenshot({path:path.join(output,'wednesday-lagoon-light.png'),animations:'allow'});
  await page.setViewportSize({width:390,height:844});await page.evaluate(()=>showView('settings'));await page.waitForTimeout(300);
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:path.join(output,'wednesday-motion-mobile.png'),animations:'allow'});
  assert.deepEqual(errors,[]);
  await fs.writeFile(path.join(output,'acceptance.json'),JSON.stringify({passed:true,checkedAt:new Date().toISOString(),captureAnimations:'allow',syntheticMicrophone:true,checks:['live panel entry clock','dialog entry and timed exit','rapid navigation resists stale responses','three palettes persist across reload','real turn progress and provider failure','mid-transition reduced motion cancellation','actual synthetic MediaRecorder reduced-motion path','OS reduced motion','no infinite animation','390px responsive preferences'],pageErrors:errors},null,2));
  await browser.close();console.log('Wednesday motion acceptance passed.');
})().catch(async error=>{console.error(error);if(browser)await browser.close();process.exit(1);});
