'use strict';
const {_electron:electron}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const path=require('node:path'),fs=require('node:fs/promises'),os=require('node:os'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process');
let runningApp;
(async()=>{
  const fixture=await fs.mkdtemp(path.join(os.tmpdir(),'aurascript-smoke-'));
  await fs.writeFile(path.join(fixture,'acceptance.py'),'print("original")\n');
  execFileSync('git',['init',fixture],{windowsHide:true});
  execFileSync('git',['-C',fixture,'config','user.name','Acceptance Fixture'],{windowsHide:true});
  execFileSync('git',['-C',fixture,'config','user.email','fixture@example.invalid'],{windowsHide:true});
  execFileSync('git',['-C',fixture,'config','commit.gpgsign','false'],{windowsHide:true});
  const output=process.env.AURA_TEST_OUTPUT||path.resolve(__dirname,'../../test-results/electron');await fs.mkdir(output,{recursive:true});
  const app=await electron.launch({executablePath:process.env.AURA_EXECUTABLE||path.resolve(__dirname,'../node_modules/electron/dist/electron.exe'),args:process.env.AURA_EXECUTABLE?[]:[path.resolve(__dirname,'..')],env:{...process.env,AURA_HEADLESS:'1',AURA_TEST_DATA:fixture+'-app-state',WEDNESDAY_URL:process.env.WEDNESDAY_URL||'http://127.0.0.1:8006'}});
  runningApp=app;
  const page=await app.firstWindow(),errors=[];page.on('pageerror',error=>{errors.push(error.message);console.error('Renderer error:',error.message);});page.on('console',message=>{if(message.type()==='error')console.error('Renderer console:',message.text());});
  await page.locator('#assistant-status').filter({hasText:'Workspace connected'}).waitFor({timeout:30000});
  await page.waitForFunction(()=>typeof monaco!=='undefined'&&typeof s!=='undefined'&&!!s.editor);
  // Native chooser is stubbed only in this isolated test process. Real IPC,
  // filesystem boundaries, Monaco, saving, terminal and Git still execute.
  await app.evaluate(({dialog},fixture)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[fixture]});},fixture);
  await page.locator('#open-folder').click();await page.getByRole('button',{name:'· acceptance.py',exact:true}).click();
  await page.waitForFunction(()=>!!s.editor.getModel());
  await page.waitForFunction(()=>monaco.editor.getModels().some(m=>m.getValue().includes('original')));
  await page.evaluate(()=>monaco.editor.getModels().find(m=>m.uri.path.endsWith('acceptance.py')).setValue('print("persisted")\n'));
  await page.keyboard.press('Control+s');
  await page.locator('#file-status').filter({hasText:'Saved · acceptance.py'}).waitFor();
  assert.equal(await fs.readFile(path.join(fixture,'acceptance.py'),'utf8'),'print("persisted")\n');
  await page.locator('#new-file').click();await page.locator('[name=name]').fill('acceptance.py');await page.locator('#dialog-submit').click();
  await page.waitForFunction(()=>document.getElementById('toast').textContent.includes('already exists'));
  assert.equal(await fs.readFile(path.join(fixture,'acceptance.py'),'utf8'),'print("persisted")\n');
  await page.locator('#dialog-close').click();
  await page.evaluate(()=>monaco.editor.getModels().find(m=>m.uri.path.endsWith('acceptance.py')).setValue('def broken(:\n'));
  await page.locator('#diagnostic-status').filter({hasText:'1 diagnostic'}).waitFor();
  await page.evaluate(()=>monaco.editor.getModels().find(m=>m.uri.path.endsWith('acceptance.py')).setValue('print("persisted")\n'));
  await page.keyboard.press('Control+s');
  await page.locator('#terminal-input').fill('git --version');await page.locator('#terminal-form button').click();
  await page.locator('#terminal-output').filter({hasText:'Process exited · 0'}).waitFor();
  await page.locator('#checkpoint').click();await page.locator('[name=message]').fill('Actual acceptance checkpoint');await page.locator('#dialog-submit').click();
  await page.waitForFunction(()=>document.getElementById('toast').textContent.includes('Checkpoint saved.'));
  assert(execFileSync('git',['-C',fixture,'log','-1','--format=%s'],{encoding:'utf8',windowsHide:true}).includes('Actual acceptance checkpoint'));
  await page.locator('#git-history').click();await page.getByRole('button',{name:/Actual acceptance checkpoint ·/}).click();
  await page.getByRole('heading',{name:'Checkpoint changes',exact:true}).waitFor();await page.locator('#dialog-close').click();
  await page.evaluate(()=>palette());
  assert(await page.locator('#dialog').evaluate(node=>node.getAnimations().some(a=>a.playState==='running')),'Command dialog did not animate');
  await page.screenshot({path:path.join(output,'aurascript-motion-command.png'),animations:'allow'});
  await page.evaluate(()=>{s.prefs.reduce_motion=true;theme();});
  assert.equal(await page.evaluate(()=>document.getAnimations().filter(a=>a.playState==='running').length),0,'Editor failed to cancel active motion');
  await page.evaluate(()=>{s.prefs.reduce_motion=false;theme();});await page.locator('[name=search]').fill('preferences');await page.getByRole('button',{name:'Preferences',exact:true}).click();
  await page.locator('[name=palette]').selectOption('lagoon');await page.locator('[name=theme]').selectOption('light');await page.locator('#dialog-submit').click();
  await page.waitForFunction(()=>document.documentElement.dataset.theme==='light');
  await page.evaluate(()=>document.fonts.ready);
  assert.equal(await page.locator('html').getAttribute('data-palette'),'lagoon');
  assert.equal(await page.evaluate(async()=> (await api('preferences')).palette),'lagoon');
  assert(await page.evaluate(()=>Array.from(document.fonts).some(face=>face.family==='Manrope'&&face.status==='loaded')),'Bundled interface font did not load');
  await page.locator('#preferences').click();
  await page.locator('[name=high_contrast]').selectOption('true');
  await page.locator('[name=reduce_motion]').selectOption('true');
  await page.locator('[name=reduce_transparency]').selectOption('true');
  await page.locator('#dialog-submit').click();
  await page.waitForFunction(()=>document.documentElement.dataset.highContrast==='true');
  await page.evaluate(()=>motion.enter(document.querySelector('.assistant')));
  assert.equal(await page.locator('.assistant').evaluate(node=>node.getAnimations().length),0,'Reduced editor pane still animates');
  assert.equal(await page.locator('.toolbar').evaluate(el=>getComputedStyle(el).backdropFilter),'none');
  assert.equal(await page.evaluate(()=>s.editor.getOption(monaco.editor.EditorOption.smoothScrolling)),false);
  assert.equal(await page.locator('.monaco-editor').first().evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(255, 255, 255)');
  await page.locator('#preferences').click();
  await page.locator('[name=high_contrast]').selectOption('false');
  await page.locator('[name=reduce_motion]').selectOption('false');
  await page.locator('[name=reduce_transparency]').selectOption('false');
  await page.locator('#dialog-submit').click();
  await page.waitForFunction(()=>document.documentElement.dataset.highContrast==='false');
  const capture=async name=>{await page.waitForFunction(()=>!document.getElementById('dialog').open);await new Promise(resolve=>setTimeout(resolve,250));const encoded=await app.evaluate(async({BrowserWindow})=>(await BrowserWindow.getAllWindows()[0].webContents.capturePage()).toPNG().toString('base64'));await fs.writeFile(path.join(output,name),Buffer.from(encoded,'base64'));};
  await capture('aurascript-desktop-light.png');
  await page.locator('#preferences').click();await page.locator('[name=theme]').selectOption('dark');await page.locator('#dialog-submit').click();
  await page.waitForFunction(()=>document.documentElement.dataset.theme==='dark');
  await capture('aurascript-desktop-dark.png');
  await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>dialog('OS motion check',[node('p','Immediate presentation')]));
  assert.equal(await page.locator('#dialog').evaluate(node=>node.getAnimations().length),0,'OS reduction did not suppress dialog');await page.locator('#dialog-close').click();
  await page.emulateMedia({reducedMotion:'no-preference'});
  assert.equal(await page.evaluate(()=>document.getAnimations().filter(a=>a.effect.getTiming().iterations===Infinity).length),0);
  assert.deepEqual(errors,[]);
  await fs.writeFile(path.join(output,'acceptance.json'),JSON.stringify({passed:true,packagedExecutable:!!process.env.AURA_EXECUTABLE,checks:['isolated native chooser','actual IPC boundary','offline Monaco','file save','exclusive creation preserves existing files','Python syntax diagnostics','terminal streaming','real Git checkpoint and diff','command palette','themes','bundled interface typography','high contrast editor and opaque chrome','reduced motion editor scrolling','live command-dialog animation','in-flight motion cancellation','persisted signature palette','immediate reduced editor motion','OS reduced motion','no continuous busy animation'],pageErrors:errors},null,2));
  await app.close();console.log('AuraScript Electron acceptance passed.');
})().catch(async error=>{console.error(error);if(runningApp){try{const page=await runningApp.firstWindow();console.error('UI:',await page.locator('#toast').textContent());console.error('Terminal:',await page.locator('#terminal-output').textContent());}catch{}await runningApp.close();}process.exit(1);});
